version: '3.9'

services:

  message-formater:

    build: .

    container_name: message_formater_api

    restart: always

    env_file:
      - .env

    expose:
      - "5007"

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.message-formater.rule=Host(`${DOMAIN}`)"

      # Entrypoint
      - "traefik.http.routers.message-formater.entrypoints=${TRAEFIK_ENTRYPOINT}"

      # Service
      - "traefik.http.services.message-formater.loadbalancer.server.port=${PORT}"

      - "traefik.http.routers.message-formater.tls=true"
      
      - "traefik.http.routers.message-formater.tls.certresolver=letsencrypt"

    networks:
      - network

networks:
  network:
    external: true